sudo: required
language: go
go:
  - 1.8
cache: yarn
services:
  - docker
install:
  - go get
  - nvm install 6
  - nvm use 6
  - yarn
script:
  - ./node_modules/.bin/webpack -p
  - go build .
  - docker build -t timojarv/gochat .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push timojarv/gochat
