sudo: required
language: go
go:
  - 1.8
cache: yarn
services:
  - docker
install:
  - go get
  - nvm install 6
  - nvm use 6
  - yarn
script:
  - ./node_modules/.bin/webpack -p
  - CGO_ENABLED=0 go build -a -ldflags '-s' -installsuffix cgo -o gochat .
  - docker build -t timojarv/gochat .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push timojarv/gochat
